stages:
  - build

build:
  stage: build
  only:
    - main
  script:
    - echo '--spring-boot-cms (main) build start--'
    - whoami
    - pwd
    - cd frontend/admin
    - docker build -t spring-boot-cms/front-admin .
    - docker run -d -p 8080:3000 --name front-admin spring-boot-cms/front-admin:latest
  tags:
    - production
