### 계정생성
POST {{host}}/api/account
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "test@gmail.com",
  "password": "1111"
}

### 계정목록 조회
GET {{host}}/api/account
Authorization: Bearer {{token}}