### 계정생성
POST {{host}}/api/account
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "username": "test2@gmail.com",
  "password": "1234"
}

### 계정목록 조회
GET {{host}}/api/account
Authorization: Bearer {{accessToken}}