GET {{host}}/api/account/myinfo
Authorization: Bearer {{token}}

###
GET {{host}}/api/account/user-feature
Authorization: Bearer {{token}}

###
GET {{host}}/api/account/admin-feature
Authorization: Bearer {{token}}

###
GET {{host}}/api/site/list
Authorization: Bearer {{token}}

###
GET {{host}}/
Authorization: Bearer {{token}}

